### ISSUE TITLE
多账号配置问题

### ISSUE THREAD

**Issue by Pauluooooo** [vv314/actions-mtz-coupons#31]
单个账号测试没有问题，但是多账号配置下就会报错：

────────── [1/2] 账号: token2 ──────────

登录过期 { code: 1, api: 'gundamLogin', msg: '未登录异常' }

😦 领取失败

────────── [2/2] 账号: token1 ──────────

程序异常 ReferenceError: ECODE is not defined
    at Object.grabCoupon (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons/takeAway.js:41:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runTask (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons.js:68:[34](https://github.com/Pauluooooo/actions-mtz-coupons/runs/8107849007?check_suite_focus=true#step:5:35))
    at async main (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons.js:1[38](https://github.com/Pauluooooo/actions-mtz-coupons/runs/8107849007?check_suite_focus=true#step:5:39):20)
    at async doJob (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:124:15)

😦 领取失败

配置格式：
[{
    "token": "FL8jIv3ow5NCBFVbMuLf-Cog6_MAAAAAxhMAAFx0fKcmqehl9LgLMKB8aNuE8GTJBWOqRttPhp1jtGEYphNXTXXXXXX",
    "tgUid": "5944XXXX"
  },{
    "token": "fzoP0m7d-MMN_V1WH9WvDWQ_DhsAAAAAxhMAAEqMk6ygSXkPxNkFcnIZAcKum8zqBVdrWnRlgfiruZI2AbPeTJctPcGDSXXXXXX",
    "tgUid": "594XXXX"
  }]

**Comment by Pauluooooo** [comment]
好像是我原来的 token 失效了，换了之后就好了。。。
