### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by jiuchu** [vv314/actions-mtz-coupons#35]
程序异常 Error: 活动配置数据获取失败: TypeError: Cannot read property '0' of null
    at getTemplateData (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons/qualityShop.js:23:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.grabCoupon (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons/qualityShop.js:28:20)
    at async runTask (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons.js:69:37)
    at async main (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons.js:138:20)
    at async doJob (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:124:15)

**Comment by nanusl** [comment]
我也出现这个问题了, 已排除token过期的可能.

**Comment by jiuchu** [comment]
> 我也出现这个问题了, 已排除token过期的可能.

可能美团改了接口
