### ISSUE TITLE
领取失败

### ISSUE THREAD

**Issue by dfbb9216** [vv314/actions-mtz-coupons#49]
失败后重试了一次，还是失败。

Run yarn start
yarn run v1.22.19
$ node index

───────────────────────────────────────
 actions-mtwm-coupons
 外卖神券天天领
────────────────────────

 Ver. 1.8.1

 Github @vv314

────────── [1/1] 账号: token1 ──────────

程序异常 Error: Payload 获取失败
    at getPayload (file:///home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/payload.js:60:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.grabCoupon (file:///home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons/takeAway.js:32:19)
    at async runTask (file:///home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons/index.js:59:34)
    at async main (file:///home/runner/work/actions-mtz-coupons/actions-mtz-coupons/lib/coupons/index.js:133:20)
    at async doJob (file:///home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:126:15)

😦 领取失败

────────── 推送通知 ──────────

[全局通知] Telegram 推送成功
Done in 5.28s.

**Comment by vv314** [comment]
main 分支已修复

**Comment by dfbb9216** [comment]
![IMG_8091(20230902-142627)](https://github.com/vv314/actions-mtz-coupons/assets/64184911/31132913-c6a3-4e69-8aec-2da03b6f17b9)
可以了
