### ISSUE TITLE
请教一下这是什么问题呢？

### ISSUE THREAD

**Issue by juneme** [vv314/actions-mtz-coupons#9]
────────── [1/1] 账号: token1 ──────────

接口异常 { code: 2, api: 'gundamGrabV3', msg: undefined }
重试: 2 次

😦 领取失败

────────── 推送通知 ──────────

/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:8
  throw err
  ^

TypeError: Cannot read property 'then' of undefined
    at /home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:149:31
    at Array.forEach (<anonymous>)
    at printNotifyResult (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:149:14)
    at main (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:179:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by angelas1qiaolezi** [comment]
一模一样
Github @vv314
/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:8

  throw err
  ^

TypeError: Cannot read property 'then' of undefined
    at /home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:149:31
    at Array.forEach (<anonymous>)
    at printNotifyResult (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:149:14)
    at main (/home/runner/work/actions-mtz-coupons/actions-mtz-coupons/index.js:179:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
────────── [1/1] 账号: token1 ──────────

接口异常 { code: 2, api: 'gundamGrabV3', msg: undefined }
重试: 2 次

😦 领取失败

**Comment by vv314** [comment]
接口异常导致程序报错的问题已修复，同时修复了 api msg 的取值问题。需要重新执行 action，查看 msg 打印，再次定位问题

**Comment by juneme** [comment]
> 接口异常导致程序报错的问题已修复，同时修复了 api msg 的取值问题。需要重新执行 action，查看 msg 打印，再次定位问题

可以正常运行了

**Comment by vv314** [comment]
releases v1.6.0
